image: node:latest

cache:
    paths:
        - node_modules

stages:
    - build
    - deploy

job_build:
    stage: build
    before_script:
        - npm install
        - export REACT_APP_BACKEND_HOST="$BACKEND_HOST"
        - echo "REACT_APP_BACKEND_HOST=$REACT_APP_BACKEND_HOST"
        - export REACT_APP_API_KEY="$API_KEY"
        - echo "REACT_APP_API_KEY=$REACT_APP_API_KEY"
    script:
        - npm run-script build

    artifacts:
        paths:
            - build/
        expire_in: 1 hour

job_deploy_to_prod:
    stage: deploy
    image: ruby:latest
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl

    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY

    only:
        - master
