export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export const REDUX_RESET_STATE = 'REDUX_RESET_STATE';

export const SEND_INSCRIPTION_REQUEST = 'SEND_INSCRIPTION_REQUEST';
export const SEND_INSCRIPTION_SUCCESS = 'SEND_INSCRIPTION_SUCCESS';
export const SEND_INSCRIPTION_FAILURE = 'SEND_INSCRIPTION_FAILURE';
